# Generated by Django 4.2.16 on 2024-11-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_capacity_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Mатериалы'},
        ),
    ]
